### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Aschroet** [pl31/whereis#6]
The seem not to work anymore. An Javascript error occurs: https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error

**Comment by pl31** [comment]
Which url are you using?

https://whereis.silverpeaks.de/ works as expected.

**Comment by Aschroet** [comment]
maybe it was a temporary problem. Works fine now also for me. --> Closed.

**Comment by Aschroet** [comment]
PS: I found that i used the URL https://www.whereis.silverpeaks.de/ which causes this problem. Maybe it should be redirected.

**Comment by pl31** [comment]
Duplicate of #5. Thanks. Should fix it soon.
